[target.'cfg(target_os = "none")']
runner = "bootimage runner"

# 
[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

# set the target to x86_64-blog_os.json
[build]
target = "x86_64-blog_os.json"
